name = "ExampleApp"
uuid = "d09fc054-0c37-4ecb-8df0-9893f685fe92"
authors = ["Morten Piibeleht <morten.piibeleht@juliahub.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
