name = "ExampleApp"
uuid = "d09fc054-0c37-4ecb-8df0-9893f685fe92"
authors = ["Morten Piibeleht <morten.piibeleht@juliahub.com> and contributors"]
version = "0.1.0"

[deps]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"

[compat]
julia = "1"
QuadGK = "2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
